### ISSUE TITLE
xkcd pattern error

### ISSUE THREAD

**Issue by Alopex8064** [webcomics/dosage#51] opened 2016-06-01 14:38 UTC
I get the following pattern error when I run dosage-2.15 on xkcd. Other comics (e.g CalvinAndHobbes) works fine.

```
$ dosage-2.15/dosage xkcd --adult
xkcd> Retrieving 1 strip (including adult content)
xkcd> ERROR: Patterns ['<\\s*[iI][mM][gG]\\s+(?:[^>]*\\s+)?[sS][rR][cC]\\s*=\\s*"(http://imgs\\.xkcd\\.com/comics/[^"]+)"[^>]*[^>]*>'] not found at URL http://xkcd.com/1688/.
```

**Comment by TobiX** [comment] 2016-06-02 10:58
This is a duplicate of #3 - this is fixed in the repository and will be fixed in the next release.

**Closed by TobiX** 2016-06-02 10:58 UTC
Labels: bug
