### ISSUE TITLE
SSL Error for ComicsKingdom Comics

### ISSUE THREAD

**Issue by ladewig** [webcomics/dosage#292] opened 2023-10-11 21:27 UTC
Starting on October 4, 2023, ComicsKingdom comics started failing for me with an SSL error:

ERROR: HTTPSConnectionPool(host='comicskingdom.com', port=443): Max retries exceeded with url: /sally-forth (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

**Comment by TobiX** [comment] 2023-10-11 23:51
Duplicate of #291, already fixed in master.

**Closed by TobiX** 2023-10-11 23:51 UTC
Labels: duplicate
