### ISSUE TITLE
lxml encoder error

### ISSUE THREAD

**Issue by Aktariel** [webcomics/dosage#88] opened 2017-05-29 05:47 UTC
Issue: trying to download The Dreamland Chronicles fails with a strange lxml error:

```
user@host:dosage$ source bin/activate
user@host:dosage$ python --version
Python 3.6.1
(dosage) user@host:dosage$ ./dosage -av TheDreamlandChronicles
TheDreamlandChronicles> Retrieving all strips
TheDreamlandChronicles> Get strip URL http://www.thedreamlandchronicles.com/
TheDreamlandChronicles> Get image URL http://www.thedreamlandchronicles.com/wp-content/uploads/2017/05/TDC-Chapter22-page169-web.jpg
TheDreamlandChronicles> Saved Comics/TheDreamlandChronicles/TDC-Chapter22-page169-web.jpg (277.20KB).
TheDreamlandChronicles> Get strip URL http://www.thedreamlandchronicles.com/comic/page-2078/
encoding error : input conversion failed due to input error, bytes 0x21 0x00 0x00 0x00
TheDreamlandChronicles> ERROR: switching encoding: encoder error, line 1, column 1 (<string>, line 1)
TheDreamlandChronicles>   File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 884, in _bootstrap
TheDreamlandChronicles>     self._bootstrap_inner()
TheDreamlandChronicles>   File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
TheDreamlandChronicles>     self.run()
TheDreamlandChronicles>   File "/Users/user/Developer/Web/dosage/dosagelib/director.py", line 80, in run
TheDreamlandChronicles>     self.getStrips(scraperobj)
TheDreamlandChronicles>   File "/Users/user/Developer/Web/dosage/dosagelib/director.py", line 94, in getStrips
TheDreamlandChronicles>     self._getStrips(scraperobj)
TheDreamlandChronicles>   File "/Users/user/Developer/Web/dosage/dosagelib/director.py", line 122, in _getStrips
TheDreamlandChronicles>     out.exception(msg)
TheDreamlandChronicles>   File "/Users/user/Developer/Web/dosage/dosagelib/output.py", line 95, in exception
TheDreamlandChronicles>     self.writelines(traceback.format_stack(), 1)
TheDreamlandChronicles>   File "/Users/user/Developer/Web/dosage/dosagelib/scraper.py", line 180, in getStrips
TheDreamlandChronicles>     for strip in self.getStripsFor(url, maxstrips):
TheDreamlandChronicles>   File "/Users/user/Developer/Web/dosage/dosagelib/scraper.py", line 190, in getStripsFor
TheDreamlandChronicles>     data = self.getPage(url)
TheDreamlandChronicles>   File "/Users/user/Developer/Web/dosage/dosagelib/scraper.py", line 466, in getPage
TheDreamlandChronicles>     tree = self._parse_page(text)
TheDreamlandChronicles>   File "/Users/user/Developer/Web/dosage/dosagelib/scraper.py", line 481, in _parse_page
TheDreamlandChronicles>     tree = html.document_fromstring(data)
TheDreamlandChronicles>   File "/Users/user/Developer/Web/dosage/lib/python3.6/site-packages/lxml/html/__init__.py", line 762, in document_fromstring
TheDreamlandChronicles>     value = etree.fromstring(html, parser, **kw)
TheDreamlandChronicles>   File "src/lxml/lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src/lxml/lxml.etree.c:79010)
TheDreamlandChronicles>   File "src/lxml/parser.pxi", line 1848, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:118341)
TheDreamlandChronicles>   File "src/lxml/parser.pxi", line 1729, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:116899)
TheDreamlandChronicles>   File "src/lxml/parser.pxi", line 1063, in lxml.etree._BaseParser._parseUnicodeDoc (src/lxml/lxml.etree.c:110886)
TheDreamlandChronicles>   File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105109)
TheDreamlandChronicles>   File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106817)
TheDreamlandChronicles>   File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105671)
TheDreamlandChronicles>   File "<string>", line 1
TheDreamlandChronicles> lxml.etree.XMLSyntaxError: switching encoding: encoder error, line 1, column 1
```

Update: I installed _backports.shutil_get_terminal_size_ and Dreamland Chronicles works with python 2.7. Am I missing a dependency for python 3.6 ??

**Comment by TobiX** [comment] 2017-06-20 06:01
I can't reproduce this problem with any of these:

- Python 3.6.1+ (default, Jun  7 2017, 19:00:24)
- Python 3.5.3+
- Python 2.7.13

Dosage has more dependencies on older Python (see [requirements.txt](https://github.com/webcomics/dosage/blob/master/requirements.txt)) since it uses newer Python features which are backported to older Python versions...

**Comment by Aktariel** [comment] 2017-07-04 05:35
I'd have to rip my entire dev setup apart to get it back to a clean slate for testing at this point, which I can't currently do. It works for me currently, so I'll call it good.. thanks!

**Comment by TobiX** [comment] 2017-07-05 14:56
I'll close this for now, feel free to reopen if the issue appears again.

**Closed by TobiX** 2017-07-05 14:56 UTC
